import = [
    "~/.config/alacritty/themes/themes/nord.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"
opacity = 0.9

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 14
